#server:
#  port: ${PORT:8080}

spring:
  application:
    name: greeting-service


greeting-service:
  greeting: "Hello"
  default-value: "World"

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'





